### ISSUE TITLE
Using L298n motor driver

### ISSUE THREAD

**Issue by KamalanathanN** [frankjoshua/diff_drive_odom_teensy#1]
Hi, 
i am using l298n Driver with Teensy 4.0 with 2 motors with quadrature encoders,
Can you please clarify on the pin connections from Teensy to the Motor Driver with respect to your code😬.

**Comment by frankjoshua** [comment]
I didn't make this as a library. It's just an example of how this could be done. To use a L298n you would need to modify lib/motor.cpp 
Right now it's set up to work with a motor driver using serial commands. I think L298n uses PWM.
